import { GuiAccordion } from "./g2_accordion";
export { GuiAccordion } from "./g2_accordion";
import { GuiButton } from "./g2_button";
export { GuiButton } from "./g2_button";
import { GuiCheckbox } from "./g2_checkbox";
export { GuiCheckbox } from "./g2_checkbox";
import { GuiCollapsible } from "./g2_collapsible";
export { GuiCollapsible } from "./g2_collapsible";
import { GuiColorPicker } from "./g2_color_picker";
export { GuiColorPicker } from "./g2_color_picker";
import { GuiCombobox } from "./g2_combobox";
export { GuiCombobox } from "./g2_combobox";
import { GuiGroup } from "./g2_group";
export { GuiGroup } from "./g2_group";
import { GuiInputColor } from "./g2_input_color";
export { GuiInputColor } from "./g2_input_color";
import { GuiInputFloat } from "./g2_input_float";
export { GuiInputFloat } from "./g2_input_float";
import { GuiInputRange } from "./g2_input_range";
export { GuiInputRange } from "./g2_input_range";
import { GuiInputVector } from "./g2_input_vector";
export { GuiInputVector } from "./g2_input_vector";
import { GuiPanel } from "./g2_panel";
export { GuiPanel } from "./g2_panel";
import { GuiRow } from "./g2_row";
export { GuiRow } from "./g2_row";
import { GuiSeparator } from "./g2_separator";
export { GuiSeparator } from "./g2_separator";
import { GuiSpacer } from "./g2_spacer";
export { GuiSpacer } from "./g2_spacer";
import { GuiTitle } from "./g2_title";
export { GuiTitle } from "./g2_title";

export default {};
window["GuiAccordion"] = GuiAccordion;
window["GuiButton"] = GuiButton;
window["GuiCheckbox"] = GuiCheckbox;
window["GuiCollapsible"] = GuiCollapsible;
window["GuiColorPicker"] = GuiColorPicker;
window["GuiCombobox"] = GuiCombobox;
window["GuiGroup"] = GuiGroup;
window["GuiInputColor"] = GuiInputColor;
window["GuiInputFloat"] = GuiInputFloat;
window["GuiInputRange"] = GuiInputRange;
window["GuiInputVector"] = GuiInputVector;
window["GuiPanel"] = GuiPanel;
window["GuiRow"] = GuiRow;
window["GuiSeparator"] = GuiSeparator;
window["GuiSpacer"] = GuiSpacer;
window["GuiTitle"] = GuiTitle;

// module.exports = [GuiAccordion, GuiCheckbox, GuiCollapsible, GuiColorPicker, GuiCombobox, GuiGroup, GuiInputColor, GuiInputFloat, GuiInputVector, GuiPanel, GuiSeparator, GuiTitle];
